export const API_ERRORS = {
    REGISTER_FAILED: 'REGISTER_FAILED',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    PRODUCTS_LOAD_FAILED: 'PRODUCTS_LOAD_FAILED',
    PRODUCT_LOAD_FAILED: 'PRODUCT_LOAD_FAILED',
    PRODUCT_SEARCH_FAILED: 'PRODUCT_SEARCH_FAILED',
    ORDERS_LOAD_FAILED: 'ORDERS_LOAD_FAILED',
    ORDER_CREATE_FAILED: 'ORDER_CREATE_FAILED',
    USERS_LOAD_FAILED: 'USERS_LOAD_FAILED',
    UNKNOWN: 'UNKNOWN'
};