export const FORM_ERRORS = {
  REQUIRED: 'REQUIRED',
  EMAIL: 'EMAIL',
  MIN_LENGTH: 'MIN_LENGTH',
  MAX_LENGTH: 'MAX_LENGTH',
  PASSWORD_FORMAT: 'PASSWORD_FORMAT',
  PASSWORD_MATCH: 'PASSWORD_MATCH',
  PHONE: 'PHONE',
  NAME: 'NAME',
  SPECIAL_CHARACTERS: 'SPECIAL_CHARACTERS',
};